"""Constants for EnerPrice."""

from datetime import timedelta

DOMAIN = "nl_day_ahead_prices"
NAME = "EnerPrice"

CONF_COUNTRY = "country"
CONF_CURRENCY = "currency"
CONF_PRIMARY_PROVIDER = "primary_provider"
CONF_ENABLE_ENTSOE = "enable_entsoe"
CONF_ENTSOE_API_TOKEN = "entsoe_api_token"
CONF_ENERGY_TAX = "energy_tax"
CONF_ENERGY_TAX_INCL_VAT = "energy_tax_incl_vat"
CONF_SUPPLIER_MARKUP_EXCL_VAT = "supplier_markup_excl_vat"
CONF_VAT = "vat"
CONF_SELECTED_SUPPLIER = "selected_supplier"
CONF_PRICE_RESOLUTION = "price_resolution"
CONF_CUSTOM_SUPPLIER_NAME = "custom_supplier_name"
CONF_CUSTOM_MONTHLY_FEE_ELECTRICITY = "custom_monthly_fee_electricity"
CONF_CUSTOM_PURCHASE_FEE_ELECTRICITY = "custom_purchase_fee_electricity"
CONF_CUSTOM_PURCHASE_FEE_INCLUDES_VAT = "custom_purchase_fee_includes_vat"
CONF_CUSTOM_SELL_FEE_ELECTRICITY = "custom_sell_fee_electricity"
CONF_CUSTOM_SELL_FEE_INCLUDES_VAT = "custom_sell_fee_includes_vat"
CONF_BEST_PERIOD_DURATION = "best_period_duration_minutes"
CONF_PEAK_PERIOD_DURATION = "peak_period_duration_minutes"
CONF_BEST_PERIOD_FLEX = "best_period_flex_percent"
CONF_PEAK_PERIOD_FLEX = "peak_period_flex_percent"
CONF_MINIMUM_GAP = "minimum_gap_minutes"
CONF_STABLE_TREND_THRESHOLD = "stable_threshold_percent"
CONF_STRONG_TREND_THRESHOLD = "strong_threshold_percent"
CONF_ALLOW_BEST_RELAXATION = "allow_best_period_relaxation"
CONF_ALLOW_PEAK_RELAXATION = "allow_peak_period_relaxation"
CONF_EXTENDED_ATTRIBUTES = "enable_extended_attributes"
CONF_CHART_HELPERS = "enable_chart_helper_entities"

DEFAULT_COUNTRY = "NL"
DEFAULT_CURRENCY = "EUR"
DEFAULT_PRIMARY_PROVIDER = "nord_pool"
DEFAULT_SELECTED_SUPPLIER = "zonneplan"
DEFAULT_PRICE_RESOLUTION = "auto"
DEFAULT_ENERGY_TAX = 0.1108
DEFAULT_ENERGY_TAX_INCL_VAT = DEFAULT_ENERGY_TAX
DEFAULT_SUPPLIER_MARKUP_EXCL_VAT = 0.01653
DEFAULT_VAT = 0.21
DEFAULT_CUSTOM_SUPPLIER_NAME = "Eigen leverancier"
DEFAULT_CUSTOM_MONTHLY_FEE_ELECTRICITY = 0.0
DEFAULT_CUSTOM_PURCHASE_FEE_ELECTRICITY = 0.0
DEFAULT_CUSTOM_PURCHASE_FEE_INCLUDES_VAT = True
DEFAULT_CUSTOM_SELL_FEE_ELECTRICITY = 0.0
DEFAULT_CUSTOM_SELL_FEE_INCLUDES_VAT = True
DEFAULT_BEST_PERIOD_DURATION = 120
DEFAULT_PEAK_PERIOD_DURATION = 60
DEFAULT_BEST_PERIOD_FLEX = 5.0
DEFAULT_PEAK_PERIOD_FLEX = 5.0
DEFAULT_MINIMUM_GAP = 0
DEFAULT_STABLE_TREND_THRESHOLD = 2.0
DEFAULT_STRONG_TREND_THRESHOLD = 10.0
DEFAULT_ALLOW_BEST_RELAXATION = True
DEFAULT_ALLOW_PEAK_RELAXATION = True
DEFAULT_EXTENDED_ATTRIBUTES = True
DEFAULT_CHART_HELPERS = False

PROVIDER_NORD_POOL = "nord_pool"
PROVIDER_ENERGY_CHARTS = "energy_charts"
PROVIDER_ENTSOE = "entsoe"
PROVIDER_CACHE = "last_known_valid_cache"

PROVIDER_NAMES = {
    PROVIDER_NORD_POOL: "Nord Pool",
    PROVIDER_ENERGY_CHARTS: "Energy-Charts",
    PROVIDER_ENTSOE: "ENTSO-E",
    PROVIDER_CACHE: "Last known valid prices cache",
}

UPDATE_INTERVAL = timedelta(hours=1)
REQUEST_TIMEOUT = 20
REQUEST_RETRIES = 2
CACHE_VERSION = 2

RUNTIME_DEFAULTS = {
    CONF_BEST_PERIOD_DURATION: DEFAULT_BEST_PERIOD_DURATION,
    CONF_PEAK_PERIOD_DURATION: DEFAULT_PEAK_PERIOD_DURATION,
    CONF_BEST_PERIOD_FLEX: DEFAULT_BEST_PERIOD_FLEX,
    CONF_PEAK_PERIOD_FLEX: DEFAULT_PEAK_PERIOD_FLEX,
    CONF_MINIMUM_GAP: DEFAULT_MINIMUM_GAP,
    CONF_STABLE_TREND_THRESHOLD: DEFAULT_STABLE_TREND_THRESHOLD,
    CONF_STRONG_TREND_THRESHOLD: DEFAULT_STRONG_TREND_THRESHOLD,
    CONF_ALLOW_BEST_RELAXATION: DEFAULT_ALLOW_BEST_RELAXATION,
    CONF_ALLOW_PEAK_RELAXATION: DEFAULT_ALLOW_PEAK_RELAXATION,
    CONF_EXTENDED_ATTRIBUTES: DEFAULT_EXTENDED_ATTRIBUTES,
    CONF_CHART_HELPERS: DEFAULT_CHART_HELPERS,
}
