"""Lovelace dashboard and automation YAML generators."""

from __future__ import annotations


def generate_dashboard_yaml(
    dashboard_type: str = "full",
    *,
    include_market_price: bool = True,
    include_all_in_price: bool = True,
    include_supplier_info: bool = True,
    include_best_periods: bool = True,
    include_price_advisor: bool = True,
    include_ev_planner: bool = False,
    include_battery_strategy: bool = False,
    theme: str = "auto",
) -> str:
    """Generate a usable manual Lovelace dashboard."""
    entities = []
    if include_market_price:
        entities.append("sensor.nl_day_ahead_prices_current_market_price")
    if include_all_in_price:
        entities.append("sensor.nl_day_ahead_prices_current_all_in_price")
    if include_price_advisor:
        entities.extend(["sensor.nl_day_ahead_price_advisor", "sensor.nl_day_ahead_price_score"])
    if include_supplier_info:
        entities.extend(
            [
                "sensor.nl_day_ahead_prices_selected_supplier",
                "sensor.nl_day_ahead_prices_effective_price_resolution",
                "sensor.nl_day_ahead_prices_current_provider",
            ]
        )
    entities.append("binary_sensor.nl_day_ahead_prices_tomorrow_prices_available")
    rows = "\n".join(f"              - {entity}" for entity in entities)
    helper_cards = ""
    if include_best_periods:
        helper_cards += """
      - type: entities
        title: Best and peak periods
        entities:
          - binary_sensor.nl_day_ahead_prices_best_price_period
          - binary_sensor.nl_day_ahead_prices_peak_price_period
          - sensor.nl_day_ahead_prices_next_best_price_period_start
          - sensor.nl_day_ahead_prices_next_peak_price_period_start
"""
    if include_ev_planner or include_battery_strategy:
        helper_cards += """
      - type: markdown
        content: >-
          Use Developer Tools > Actions to run the EV charging or battery
          strategy planner. The returned planning data can be used in scripts.
"""
    theme_line = "" if theme == "auto" else f"theme: {theme}\n"
    columns = 1 if dashboard_type == "compact" else 2
    return f"""{theme_line}title: EnerPrice
views:
  - title: Energy advisor
    path: energy-advisor
    type: sections
    max_columns: {columns}
    sections:
      - type: grid
        cards:
          - type: entities
            title: EnerPrice
            entities:
{rows}
          - type: custom:apexcharts-card
            graph_span: 48h
            span:
              start: day
            series:
              - entity: sensor.nl_day_ahead_prices_current_market_price
                name: Market
                data_generator: |
                  return entity.attributes.prices.map(p => [new Date(p.time).getTime(), p.price]);
              - entity: sensor.nl_day_ahead_prices_current_all_in_price
                name: All-in
                data_generator: |
                  return [...entity.attributes.all_in_prices_today, ...entity.attributes.all_in_prices_tomorrow]
                    .map(p => [new Date(p.time).getTime(), p.price]);
{helper_cards}"""


def generate_automation_yaml(
    automation_type: str,
    target_entity: str,
    *,
    notify_service: str = "notify.notify",
    duration_minutes: int = 120,
    deadline: str | None = None,
) -> str:
    """Generate an editable Home Assistant automation."""
    binary = {
        "boiler_best_period": "binary_sensor.nl_day_ahead_prices_best_price_period",
        "notify_expensive_period": "binary_sensor.nl_day_ahead_expensive_energy_now",
        "notify_cheap_period": "binary_sensor.nl_day_ahead_cheap_energy_now",
        "appliance_best_window": "binary_sensor.nl_day_ahead_prices_best_price_period",
        "battery_charge_discharge": "binary_sensor.nl_day_ahead_prices_best_price_period",
        "ev_charge_before_deadline": "binary_sensor.nl_day_ahead_prices_best_price_period",
    }[automation_type]
    is_notification = automation_type.startswith("notify_")
    action = (
        f"""      - action: {notify_service}
        data:
          message: "EnerPrice notification for {target_entity}."
"""
        if is_notification
        else f"""      - action: homeassistant.turn_on
        target:
          entity_id: {target_entity}
"""
    )
    deadline_note = f"\n# Desired deadline: {deadline}" if deadline else ""
    return f"""alias: EnerPrice {automation_type.replace("_", " ")}
description: Generated by EnerPrice; review entity IDs before enabling.
triggers:
  - trigger: state
    entity_id: {binary}
    to: "on"
conditions: []
actions:
{action}mode: single
# Suggested duration: {duration_minutes} minutes{deadline_note}
"""
